### PR TITLE
added kitsune theme and didnt skid ravenweave's aura

### PR DESCRIPTION
**Pull request by larryngton**
;3

### CODE REVIEW

**Comment by larryngton** [comment]
> i mean, it's nice to have a not broken aura but i do feel a bit bad just pasting ravenweave's after i failed to make a half decent aura for forever furthermore im pretty sure there is a bit more you have to do to get it working but i'll test it one day TM (you can see im very ahead of pull requests and have much care for this project these days) theme does seem nice tho

I made a separate module for ravens aura so when you make the existing one even better we can delete ravens (btw your aura is amazing for hvhing and it will also be good for verus if you add auto blocks good job 👍)

**Comment by larryngton** [comment]
update so the module gets rendered in the clickgui

**Comment by Tryflle** [comment]
oh yeah I forgot about this
active stormy development and focusing on school moment

**Comment by larryngton** [comment]
> oh yeah I forgot about this active stormy development and focusing on school moment

💀

**Comment by Tryflle** [comment]
Syz is working on a mega pr, killaura is being improved within that

**Comment by larryngton** [comment]
> Syz is working on a mega pr, killaura is being improved within that

let him cook then 🔥

**Comment by fjer9** [comment]
wtf is this bro have u even tried compiling it??? all u did is paste the code and rename it from ravenweave to stormy. hell you couldn't even paste it right cuz what is this supposed to be

image

you didnt even implement the theme. you just added a color code that is never fucking used

im surprised you even found the button to make a pr like holy shit

**Comment by larryngton** [comment]
@Tryflle this fuck got banned and doesnt know that this is a fucking pull request and changes are to be made 😭 im literally saying that i skidded the aura

**Comment by Tryflle** [comment]
He has a point dude. Your code wouldn't work at all now that I look at it. The killaura class is defined 3 times now lmfaooooooooo. Also yes, kitsune theme is unused. I'll probably add it after syz's pr myself though.

**Pull request closed without merging**
